//
//  SdcardScheduleProtocol.h
//  P2PCamera
//
//  Created by Tsang on 13-1-14.
//
//

#import <Foundation/Foundation.h>

@protocol SdcardScheduleProtocol <NSObject>
@optional
-(void)sdcardScheduleParams:(NSString *)did Tota:(int)total  RemainCap:(int)remain SD_status:(int)status Cover:(int) cover_enable TimeLength:(int)timeLength FixedTimeRecord:(int)ftr_enable RecordSize:(int)recordSize record_schedule_sun_0:(int) record_schedule_sun_0 record_schedule_sun_1:(int) record_schedule_sun_1 record_schedule_sun_2:(int) record_schedule_sun_2 record_schedule_mon_0:(int) record_schedule_mon_0 record_schedule_mon_1:(int) record_schedule_mon_1 record_schedule_mon_2:(int) record_schedule_mon_2 record_schedule_tue_0:(int) record_schedule_tue_0 record_schedule_tue_1:(int) record_schedule_tue_1 record_schedule_tue_2:(int) record_schedule_tue_2 record_schedule_wed_0:(int) record_schedule_wed_0 record_schedule_wed_1:(int) record_schedule_wed_1 record_schedule_wed_2:(int) record_schedule_wed_2 record_schedule_thu_0:(int) record_schedule_thu_0 record_schedule_thu_1:(int) record_schedule_thu_1 record_schedule_thu_2:(int) record_schedule_thu_2 record_schedule_fri_0:(int) record_schedule_fri_0 record_schedule_fri_1:(int) record_schedule_fri_1 record_schedule_fri_2:(int) record_schedule_fri_2 record_schedule_sat_0:(int) record_schedule_sat_0 record_schedule_sat_1:(int) record_schedule_sat_1 record_schedule_sat_2:(int) record_schedule_sat_2;
//获取录像计划
-(void)recordSchedule:(NSString *)cameraUID Record_plan1:(int)record_plan1 Record_plan2:(int)record_plan2 Record_plan3:(int)record_plan3 Record_plan4:(int)record_plan4 Record_plan5:(int)record_plan5 Record_plan6:(int)record_plan6 Record_plan7:(int)record_plan7 Record_plan8:(int)record_plan8 Record_plan9:(int)record_plan9 Record_plan10:(int)record_plan10 Record_plan11:(int)record_plan11 Record_plan12:(int)record_plan12 Record_plan13:(int)record_plan13 Record_plan14:(int)record_plan14 Record_plan15:(int)record_plan15 Record_plan16:(int)record_plan16 Record_plan17:(int)record_plan17 Record_plan18:(int)record_plan18 Record_plan19:(int)record_plan19 Record_plan20:(int)record_plan20 Record_plan21:(int)record_plan21 Record_plan_enable:(int)record_plan_enable;

-(void)motionRecordSchedule:(NSString *)cameraUID motion_record_plan1:(int)motion_record_plan1 motion_record_plan2:(int)motion_record_plan2 motion_record_plan3:(int)motion_record_plan3 motion_record_plan4:(int)motion_record_plan4 motion_record_plan5:(int)motion_record_plan5 motion_record_plan6:(int)motion_record_plan6 motion_record_plan7:(int)motion_record_plan7 motion_record_plan8:(int)motion_record_plan8 motion_record_plan9:(int)motion_record_plan9 motion_record_plan10:(int)motion_record_plan10 motion_record_plan11:(int)motion_record_plan11 motion_record_plan12:(int)motion_record_plan12 motion_record_plan13:(int)motion_record_plan13 motion_record_plan14:(int)motion_record_plan14 motion_record_plan15:(int)motion_record_plan15 motion_record_plan16:(int)motion_record_plan16 motion_record_plan17:(int)motion_record_plan17 motion_record_plan18:(int)motion_record_plan18 motion_record_plan19:(int)motion_record_plan19 motion_record_plan20:(int)motion_record_plan20 motion_record_plan21:(int)motion_record_plan21 Motion_record_plan_enable:(int)motion_record_plan_enable;

-(void)motionPushSchedule:(NSString *)cameraUID motion_push_plan1:(int)motion_push_plan1 motion_push_plan2:(int)motion_push_plan2 motion_push_plan3:(int)motion_push_plan3 motion_push_plan4:(int)motion_push_plan4 motion_push_plan5:(int)motion_push_plan5 motion_push_plan6:(int)motion_push_plan6 motion_push_plan7:(int)motion_push_plan7 motion_push_plan8:(int)motion_push_plan8 motion_push_plan9:(int)motion_push_plan9 motion_push_plan10:(int)motion_push_plan10 motion_push_plan11:(int)motion_push_plan11 motion_push_plan12:(int)motion_push_plan12 motion_push_plan13:(int)motion_push_plan13 motion_push_plan14:(int)motion_push_plan14 motion_push_plan15:(int)motion_push_plan15 motion_push_plan16:(int)motion_push_plan16 motion_push_plan17:(int)motion_push_plan17 motion_push_plan18:(int)motion_push_plan18 motion_push_plan19:(int)motion_push_plan19 motion_push_plan20:(int)motion_push_plan20 motion_push_plan21:(int)motion_push_plan21 motion_push_enable:(int)motion_push_enable;
@end